### ISSUE TITLE
Suppression of final primitive fields doesn't work.

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#105]
Suppression of final primitive fields doesn't work. The calls are never
intercepted by the MockGateway for some reason. Perhaps it's something
wrong with Javassist?

**Comment by thekingnothing** [comment]
Tests has been added.

**Comment by thekingnothing** [comment]
The issue cannot be fixed. The javac inlines values of final static int/long/boolean during compile time. So these values cannot be suspected.
