### ISSUE TITLE
Incompatibility with SpringFramework : runner conflict

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#176]
_From [souquier...@gmail.com](https://code.google.com/u/104165156136980705005/) on September 11, 2009 09:28:42_

What steps will reproduce the problem? 1. Using Dependency injection (@Autowired or extends
JunitSpringDependencyInjection...) in my Junit Test
2. While using @Runwith(PowermockRunner.java) What is the expected output? What do you see instead? ClassCastException: An awesome Can't cast "myclass.java" to "myclass.java" What version of the product are you using? On what operating system? Last one  : 1.2.5 with eclipse on Ubuntu 9.04 Please provide any additional information below. Already triied to ignore involved Paths with PowerMock ignore....

_Original issue: http://code.google.com/p/powermock/issues/detail?id=156_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 11, 2009 03:03:08_

PowerMock's main intention is to be used in unit tests where you want to isolate the
code under test from an environment. What you're probably doing is an integration
test. Never the less it would be nice to get it working so I'll add it as an
enhancement request

**Status:** Accepted  
  **Labels:** -Type-Defect -Priority-Medium Type-Enhancement Priority-Low Milestone-Future

**Comment by johanhaleby** [comment]
_From [souquier...@gmail.com](https://code.google.com/u/104165156136980705005/) on September 11, 2009 08:32:56_

It's not an integration test, the class i want to test is a Spring bean in our
application.

I manage to resolve this by using Default constructor and set manually all necessary
properties.

Yes, it would be an enhancement, less work for the same result, I suppose it requires
a Spécifique runner "Spring compatible". Like @RunWith( SpringJUnit4ClassRunner.class
), allowing the use of injection. But it's a quite complicated for me when it comes
to JVM consideration...

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 17, 2010 00:22:06_

Hmm.. Could you create an example that demonstrates the issue?

**Comment by johanhaleby** [comment]
_From [eva.mukh...@gmail.com](https://code.google.com/u/114562788659726350887/) on May 26, 2010 00:49:25_

Is this enhancement done?
I intend to use PowerMockito's static mocking capability in integration tests ran
with SpringJunit4ClassRunner...

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 26, 2010 01:14:47_

Try the PowerMockRule , that's the only viable option right now that I can think of.

**Comment by johanhaleby** [comment]
_From [samueldo...@gmail.com](https://code.google.com/u/101746029160237510955/) on October 04, 2010 13:28:14_

There are some really odd issues with running Spring Integration tests and PowerMock.
I'm using TestNG with a suite.xml file and just having PowerMock scanned in the classpath is doing something odd.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 05, 2010 03:42:09_

What do you mean by "just having PowerMock scanned ..."?

Are you using the rule?

**Comment by johanhaleby** [comment]
_From [dietrich...@gmail.com](https://code.google.com/u/115844465204731828022/) on November 14, 2010 22:40:02_

I probably run into the same issue, using spring's runner with PowerMockRule .

I want to create a static mock for slf4j LoggerFactory in a spring test, and I get "cannot subclass final class LoggerFactory".

If I remove the spring runner and use the PowerMock runner instead of the rule, the mock is created properly.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 14, 2010 23:31:36_

We have plans to make a second version of the PowerMock rule that uses e.g. XStream as deep-cloner instead of in-memory Objenesis state cloning which unfortunately is not very stable. I'm not sure if it'll solve your problem though, it could be that you may need to depend on the @PowerMockIgnore annotation...

**Comment by johanhaleby** [comment]
_From [dietrich...@gmail.com](https://code.google.com/u/115844465204731828022/) on November 15, 2010 07:32:04_

Thank you for your answer. What would I have to ignore then?

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on April 10, 2011 06:00:04_

I've recently created a new project called powermock-module-junit4-agent which bootstraps using a javaagent instead of classloaders. Please help us by checking out PowerMock from trunk and try if the new project works for you. Depend on:

\<groupId>org.powermock</groupId>
\<artifactId>powermock-module-junit4-rule-agent</artifactId>
\<version>1.4.9-SNAPSHOT</version>

in Maven. Then you use the @ PowerMockRule as usually: 

@Rule
public PowerMockRule powermock = new PowerMockRule ();

**Labels:** -Priority-Low -Milestone-Future Priority-High Milestone-Release1.5

**Comment by johanhaleby** [comment]
_From [keanu.p...@gmail.com](https://code.google.com/u/102649359904805506680/) on July 06, 2012 10:31:49_

I'm really hope this issue will be fixed on next release, please.

**Comment by thekingnothing** [comment]
PowerMock could successful use with Spring via `@PowerMockRunnerDelegate`.
