### ISSUE TITLE
StringBuffer is not being mocked

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#304]
_From [nisabek](https://code.google.com/u/nisabek/) on October 12, 2010 15:52:15_

What steps will reproduce the problem? 1. Create class with the following method 
  
  public static void tuftaMethod(){
        StringBuffer buff = new StringBuffer();
        buff.toString();
    }

2.Create test for the method with the following body
    
    @Test
    public void testTuftaMehtod() throws Exception {
        StringBuffer buff = createMock(StringBuffer.class);
        expectNew(StringBuffer.class).andReturn(buff);
        replayAll();

        JustAskNotifierJob.tuftaMethod();

        verifyAll();

    }
3. Run the test

The mock of StringBuffer is not being created the test passes(if a MOCK had been created it would fail) and the debug shows that a REAL StringBuffer object has been created instead of EasyMock .class.

We are using powermock-easymock-full.jar v 1.4.5

Thanks in advance.

Regards,
Nune.

_Original issue: http://code.google.com/p/powermock/issues/detail?id=284_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 12, 2010 10:54:50_

What do you prepare for test?

**Comment by johanhaleby** [comment]
_From [nisabek](https://code.google.com/u/nisabek/) on October 12, 2010 21:18:37_

Only the class that is being tested. I tried to prepare StringBuffer but it didn't help.

**Comment by johanhaleby** [comment]
_From [aznaur...@gmail.com](https://code.google.com/u/113632801973503441997/) on October 12, 2010 23:15:27_

The same thing is for StringBuilder.

**Comment by johanhaleby** [comment]
_From [mishail.mishail](https://code.google.com/u/mishail.mishail/) on October 13, 2010 22:22:54_

BTW, it's impossible to mock toString() method of any object, it's EasyMock limitation  (see http://easymock.org/EasyMock3_0_Documentation.html#Object_Methods )

**Comment by johanhaleby** [comment]
_From [nisabek](https://code.google.com/u/nisabek/) on October 13, 2010 23:57:44_

Sorry the issue is invalid. the problem was the toString() method and not mocking of StringBuffer. 
What confuses is that the debug shows that the mocked object is of type StringBuffer and not of EasyMock type. but other expectations (except of toString) work on it.

Thanks.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 14, 2010 05:21:47_

**Status:** Invalid

**Comment by johanhaleby** [comment]
_From [avinash....@gmail.com](https://code.google.com/u/114398522819641393914/) on September 07, 2011 03:49:35_

I am not able to create mock object for StringBuffer, what is the solution for this??


I am getting the below error!

java.lang.IllegalArgumentException: Cannot subclass final class class java.lang.StringBuffer

**Comment by ogoletti** [comment]
I'd like to reopen this issue. 
I encountered a similar behavior. 
Just try this in a test : 
```
        StringBuffer mockedSB = PowerMockito.mock(StringBuffer.class);
        System.out.println(mockedSB.getClass());
```
It prints 
`class java.lang.StringBuffer
`
instead of something like `replica.java.lang.StringBuffer$$PowerMock0$$EnhancerByMockitoWithCGLIB$$c9b48ec8`
I digged with a debugger and it's here in DefaultMockCreator.java
```
        T mock = mockData.getMock();
        if (isFinalJavaSystemClass(type) && !isStatic) {
            mock = Whitebox.newInstance(type);
            DefaultFieldValueGenerator.fillWithDefaultValues(mock);
        }
```
when `Whitebox.newInstance`is called that the mock is replaced by an acutal instance of StringBuffer. 

I'm using powermock-api-mockito2-1.6.6.jar

Thanks,

O.
