### ISSUE TITLE
mock(UUID.class) returns an actual UUID instance and not a mock.

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#374]
_From [marceloverdijk](https://code.google.com/u/marceloverdijk/) on November 02, 2011 22:45:25_

UUID uuid = org.powermock.api.mockito.PowerMockito.mock(UUID.class) returns an actual UUID instance and not a mock.

I have this class:

public class SecurityService {
	public String generatePerishableToken() {
	    return UUID.randomUUID().toString().replaceAll("-", "");
	}
}

and the test class looks like:

@RunWith(PowerMockRunner.class)
@PrepareForTest({ SecurityService.class })
public class SecurityServiceTest {

	private SecurityService service;
	private UUID uuid;

	@Before
	public void setUp() {
		service = new SecurityService();
		uuid = mock(UUID.class);
	}

	@Test
	public void testGeneratePerishableToken() {
		// given
		mockStatic(UUID.class);
		given(UUID.randomUUID()).willReturn(uuid);
		given(uuid.toString()).willReturn("my-perishable-token");

		// when
		String actual = service.generatePerishableToken();

		// then
		assertEquals("myperishabletoken", actual);
		// TODO verify
	}
}

_Original issue: http://code.google.com/p/powermock/issues/detail?id=354_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 03, 2011 13:48:55_

It's not possible to solve. I've added some work-around to PowerMock trunk which makes you do like this:

    @Test
    public void mockingUUIDWorks() throws Exception {
        // given
        final UUID mock = mock(UUID.class);
        mockStatic(UUID.class);
        given(UUID.randomUUID()).willReturn(mock);

		// when
		String actual = new SystemClassUser().generatePerishableToken();

		// then
		assertEquals("00000000000000000000000000000000", actual);
    }

**Status:** Fixed

**Comment by thekingnothing** [comment]
I added example how to mock UUID

[Class that use UUID](https://github.com/powermock/powermock-examples-maven/blob/master/system-classes/src/main/java/example/powermock/systemclasess/service/DocumentService.java)
[Test](https://github.com/powermock/powermock-examples-maven/blob/master/system-classes/src/test/java/example/powermock/systemclasess/service/DocumentServiceTest.java)

**Comment by anuragsidana** [comment]
@johanhaleby  Still Im facing the issue after doing the impl suggested by you. 
Actual UUID is being return in each call.

**Comment by Ojasv-Singh-Zeotap** [comment]
Was facing the same issue with these.

Class function
```
public static String getDataflowAssetName(Long orgId, Region region) {
        return UUID.randomUUID().toString(),
    }
```

Test Function
```
@RunWith(PowerMockRunner.class)
@PrepareForTest({FileDropService.class})
public class FileDropServiceTest {
@Before
    public void setUp() {
}
@Test
    public void t2_2() {
        String uuid = UUID.randomUUID().toString();
        PowerMockito.mockStatic(UUID.class);
        PowerMockito.when(UUID.randomUUID().toString()).thenReturn(uuid);
        CommonUtils commonUtils = new CommonUtils();
        String name = commonUtils.uuid();
        Assert.assertEquals(uuid, name);
    }
}
```
Turns out needed to add  `CommonUtils.class` in @PrepareForTest({FileDropService.class}) --> `@PrepareForTest({FileDropService.class, CommonUtils.class})`
