### ISSUE TITLE
PrepareForTest javadocs incorrect

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#431]
_From [brian.he...@gmail.com](https://code.google.com/u/101263473345426190625/) on November 21, 2012 22:22:37_

What steps will reproduce the problem? 1. look at the docs @ http://powermock.googlecode.com/svn/docs/powermock-1.4.12/apidocs/org/powermock/core/classloader/annotations/PrepareForTest.html 2. try to write code using the information contained therein regarding wildcarded package names:
    You can also prepare whole packages for test by using wildcards:
     @PrepareForTest("com.mypackage.*") What is the expected output? What do you see instead? This should be compilable.  It is not.  Error: 
    Type mismatch: cannot convert from String to Class<?>[] What version of the product are you using? On what operating system? 1.4.12 Please provide any additional information below. Perhaps correct usage?:
    @PrepareForTest(fullyQualifiedNames={"com.mypackage.*"})

_Original issue: http://code.google.com/p/powermock/issues/detail?id=411_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 29, 2012 10:42:29_

You're right! Please provide a patch.

**Comment by dlazerka** [comment]
Vote +1
