### ISSUE TITLE
Static mocks throw java.lang.VerifyError when using Java 7 language features.

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#447]
_From [nho...@gmail.com](https://code.google.com/u/118405187479428795965/) on January 30, 2013 19:29:25_

What steps will reproduce the problem? 1. Class uses Java 7 language features
2. PowerMock mocks with mockStatic 
3. No profit

What is the expected output?
Test runs

What do you see instead?
java.lang.VerifyError: Stack map does not match the one at exception handler 75 in method org.app.Foo.bar()Ljava/lang/String; at offset 72

In the Foo class the following does NOT run

try {
    return "baz";
} catch (FileSystemAlreadyExistsException | ConcurrentModificationException e) {
    System.out.println("error");
    return null;
}

Changing it to this works fine

try {
    return "baz";
} catch (FileSystemAlreadyExistsException e) {
    System.out.println("error");
    return null;
} catch (ConcurrentModificationException e) {
    System.out.println("error");
    return null;
} What version of the product are you using? On what operating system? PowerMock 1.5
Mockito 1.9.5
javassist 3.17.1-GA
java 1.7.0_11 x64
Windows 7 x64
Project target / language level / compiler: 1.7

Test case attached

**Attachment:** [PowerMockTest.zip](http://code.google.com/p/powermock/issues/detail?id=427)

_Original issue: http://code.google.com/p/powermock/issues/detail?id=427_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on February 02, 2013 03:05:54_

I suspect that this is a Javassist issue.. Perhaps you could report this to the Javassist team?

**Comment by johanhaleby** [comment]
_From [nho...@gmail.com](https://code.google.com/u/118405187479428795965/) on February 05, 2013 12:44:12_

Reproduced w/o powermock and reported at https://issues.jboss.org/browse/JASSIST-190

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on February 06, 2013 04:27:32_

Thanks for your help. I'll mark it as "WontFix" if it's ok by you. When Javassist releases a new version it'll of course be shipped with PowerMock.

**Status:** WontFix

**Comment by nazymko** [comment]
Hi
Guys from javassist fix it https://issues.jboss.org/browse/JASSIST-190 - CLOSED
When you will be able to deliver new version with fix of this bug ?

**Comment by johanhaleby** [comment]
PowerMock is already using the latest version of Javassist (3.20)
