### ISSUE TITLE
MockClassLoader#loadMockClass fails to preserve original ProtectionDomain of classes prepared for test

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#564]
_From [rliesenf...@gmail.com](https://code.google.com/u/112150874253264777993/) on March 09, 2015 19:33:10_

What steps will reproduce the problem? 1. Try to use another bytecode manipulation tool together with PowerMock, for example, JaCoCo. What is the expected output? What do you see instead? The other tool should still be able to properly instrument classes that got prepared for test by PowerMock. Doing so might require that the original ProtectionDomain of the prepared class be preserved in the copy generated by MockClassLoader. JaCoCo, in particular, checks that the ProtectionDomain of each class has a code source location, to determine whether it's a legitimate ".class" file from the codebase, or a dynamically generated class which only exists at runtime (and therefore should not be instrumented for coverage).

This can affect other tools, such as JMockit Coverage. What version of the product are you using? On what operating system? PowerMock 1.6.1, on Windows 7 (the OS or JDK version should not matter here). Please provide any additional information below. There is already a JaCoCo issue open: https://github.com/jacoco/jacoco/issues/294 I believe the fix should be relatively simple: PowerMock will need to save somewhere the ProtectionDomain of each class prepared for test (say, in a Map<String, ProtectionDomain>) of prepared class names), so that it can recover the PD and pass it in the call to "ClassLoader#defineClass" at the end of "loadMockClass". This should solve the problem without any backward-compatibiliy issues.

_Original issue: http://code.google.com/p/powermock/issues/detail?id=544_

**Comment by johanhaleby** [comment]
_From [rmcr...@gmail.com](https://code.google.com/u/117897717447362743606/) on July 07, 2015 07:47:15_

Any idea when this issue might be addressed?

**Comment by rspython** [comment]
Is this bug something which may get fixed soon?  it's quite frustrating not being able to use such a useful and flexible tool as powermock with jacoco, which is our and sonar's chosen coverage tool.

**Comment by johanhaleby** [comment]
Please help out if you know how to modify the classloader to achieve this. Or if you find any resources that can help me solving it.

**Comment by astafev** [comment]
Hello, I believe this commit: https://github.com/astafev/powermock/commit/6f32a1e97ea647cf67aada6a2259b07d5e32d6c7 fixes the issue. May I ask you to review/adopt it?

**Comment by johanhaleby** [comment]
Please add it as a pull request.

**Comment by mfarid** [comment]
Looks like it has been added to the master branch.

I would like to use this feature but I am getting error while fetching the 1.6.4-SNAPSHOT version. Here are the details of the error: 

[ERROR] Failed to execute goal on project spoon-client: Could not resolve dependencies for project com.squareup.spoon:spoon-client:jar:1.2.1-SNAPSHOT: Could not find artifact org.powermock:powermock-api-mockito:jar:1.6.4-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]

Please suggest how can I get this fix working for my application.

**Comment by johanhaleby** [comment]
I haven't published a snapshot with this feature included yet.

**Comment by flemontreer** [comment]
Hi I am still experiencing the problem with version 1.6.4 of PowerMock, I am trying in on an Android project, PowerMock with EasyMock, launching tests with PowerMockRunner.
Result is still 0% code coverage.

**Comment by astafev** [comment]
I don't develop for Android, could you share sample project and instructions to reproduce the problem?

**Comment by flemontreer** [comment]
Hi !
Here is a sample project which shows the problem :

[Github sample](https://github.com/flemontreer/powermock_easymock_jacoco/tree/master)

I wrote a first analysis in Readme file

**Comment by astafev** [comment]
Hi, as far as I see, the reason is different from current thread, take a look here: https://github.com/jacoco/eclemma/issues/15. Probably, it can't be fixed, at least not on powermock side.

May I ask to check the following: replace class2 in Class1Test.java with real implementation and check if Class2 will be covered in resulting report. If everything goes fine, Class2 should be covered with powermock version 1.6.4.

**Comment by jameyg42** [comment]
6f32a1e97 only seems to preserve the protection domain for unmocked classes, which unfortunately means we can't get the protection domain of the class under test (which MockClassLoader considers mocked).  Perhaps my real question is "why is the class under test considered mocked" (i.e. not applicable to this thread), but is there any reason why the protection domain isn't preserved for the mocked class too (glancing at ClassLoader.defineClass(), any reason for not passing the ProtectionDomain along isn't obvious)?

**Comment by astafev** [comment]
@jameyg42 hi
> which unfortunately means we can't get the protection domain of the class under test (which MockClassLoader considers mocked)

I either didn't understand that, or disagree, if you're "preparing for test" class under test, then yes, but it's not necessary. 

According to my understanding of protection domain concept, providing it to mocked class isn't right. Besides it won't help to get coverage from jacoco. 
If I remember it right it's because jacoco compares hashes of class in runtime and class in filesystem and that hashes will be different.
