### ISSUE TITLE
Problem with try without sentences

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#569]
_From [voyadomi...@gmail.com](https://code.google.com/u/110765734015180001731/) on June 11, 2015 13:41:01_

What steps will reproduce the problem? mockStatic of class with a try (style Java7) without sentences. For exemple:
PowerMockito.mockStatic(ServiceLocator.class);

and ServiceLocator.java contains:
try (Connection c = ServiceLocator.ds.getConnection()) {
} catch (Exception e) {
throw new ServiceLocatorInitException(msg, e);
}

I obtain the exception in the attach. What version of the product are you using? On what operating system? \<dependency>
  \<groupId>org.powermock</groupId>
  \<artifactId>powermock-module-junit4</artifactId>
  \<version>1.6.0</version>
  \<scope>test</scope>
\</dependency>
		
\<dependency>
  \<groupId>org.powermock</groupId>
  \<artifactId>powermock-api-mockito</artifactId>
  \<version>1.6.0</version>
  \<scope>test</scope>
\</dependency>

I test with 1.6.2 and same problem. Windows and Lynux.

**Attachment:** [excepcion.txt](http://code.google.com/p/powermock/issues/detail?id=549)

_Original issue: http://code.google.com/p/powermock/issues/detail?id=549_

**Comment by johanhaleby** [comment]
_From [voyadomi...@gmail.com](https://code.google.com/u/110765734015180001731/) on June 11, 2015 04:43:48_

And this runs fine:
                try (Connection c = ServiceLocator.ds.getConnection()) {
               	    int i=0;
                } catch (Exception e) {
                    String msg = "Error al inicializar la conexion a la BBDD.";
                }

**Comment by thekingnothing** [comment]
Not enough information. Log with exception has been lost during migration from google code to GitHub.
