### ISSUE TITLE
Enable @PrepareForTest on enums

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#572]
_From [Chessra...@gmail.com](https://code.google.com/u/114145844974486262972/) on July 11, 2015 22:01:18_

What steps will reproduce the problem? 
1. Define an enum class with a method that will call the constructor of another class.
2. Define a test for this enum (mock the constructor call) and mark it to be tested with @PrepareForTest.
3. Run the test. 

What is the expected output? 
What do you see instead? 
I expect the constructor call to be replaced by the mock, but it is just executed normally. 
What version of the product are you using? On what operating system? 
1.6.2 on Windows
Please provide any additional information below. 

I have attached a code example from the greenmail project.

**Attachment:** 

- https://storage.googleapis.com/google-code-attachments/powermock/issue-552/comment-0/StoredMessageCollectionFactory.java
- https://storage.googleapis.com/google-code-attachments/powermock/issue-552/comment-0/StoredMessageCollection.java
- https://storage.googleapis.com/google-code-attachments/powermock/issue-552/comment-0/MapBasedStoredMessageCollection.java
- https://storage.googleapis.com/google-code-attachments/powermock/issue-552/comment-0/StoredMessageCollectionFactoryTest.java

**Comment by thekingnothing** [comment]
It was incorrect usage. Each enum value it's inline class, so this inline classes also should be added to `@PrepareForTest` like : 
`@PrepareForTest(value = {EnumWithConstructor.class, SomeObjectInterfaceImpl.class}, fullyQualifiedNames = "samples.enummocking.EnumWithConstructor$1")`
