### ISSUE TITLE
@runwith doesn't work with junit

### ISSUE THREAD

**Issue by LuqunInfo** [jayway/powermock#573]
1.only two files:
src
----powermock
--------Employee.java
--------EmployeeTest.java

2.EmployeeTest.java is very simple:
@RunWith(PowerMockRunner.class)
@PrepareForTest(Employee.class)
public class EmployeeTest {
	@Test
	public void testGetName() {
		Employee employee = new Employee();
		String name = "luqun";
		employee.setName(name);
		Assert.assertEquals(name, employee.getName());
	}
}

3. it doesn't work: 

in command:
java -Djava.ext.dirs=./lib org.junit.runner.JUnitCore powermock.EmployeeTest

then:

There was 1 failure:
1) initializationError(powermock.EmployeeTest)
java.lang.ClassNotFoundException: powermock.EmployeeTest
        at java.net.URLClassLoader$1.run(Unknown Source)

**Comment by johanhaleby** [comment]
What version of PowerMock and JUnit are you using?

**Comment by LuqunInfo** [comment]
junit-4.12.jar
mockito-all-1.10.19.jar
powermock-mockito-1.6.2-full.jar

**Comment by LuqunInfo** [comment]
I know why:

in classpath the order is :

powermock**.jar:junit**.jar

**Comment by johanhaleby** [comment]
Glad you sorted it out.
