### ISSUE TITLE
cannot run individual test method when using powermock in combination with spring

### ISSUE THREAD

**Issue by OscarScholten** [jayway/powermock#578]
Hi all,

When using PowerMock in combination with Spring such as in the below example, when you try to run an individual test method using the below command (or using for instance IntelliJ), for some reason all tests in the class are executed.

I'm using PowerMock 1.6.2.

Cheers, Oscar
# example
```java
@RunWith(PowerMockRunner.class)
@PowerMockRunnerDelegate(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = {"classpath:/spring.xml"})
public class TestPowerMockRunnerDelegate {

    @Test
    public void testOne() {
    }

    @Test
    public void testTwo() {
    }
}
```
# command
```
mvn test -Dtest=TestPowerMockRunnerDelegate#testOne
```

**Comment by chang-chao** [comment]
Faced with the same problem,after some source reading, the reason is that DelegatingPowerMockRunner does not implement the <code>org.junit.runner.manipulation.Filterable</code> interface.

Does any developers have any planning to implement it?
if not,I would do a try.

**Comment by johanhaleby** [comment]
Would be great if you could give it a shot! I'll be happy to include it in
powermock if you can get it working.

**Comment by OscarScholten** [comment]
Hi there - thanks for the fix! Tested it here in my local project and works as-expected :-)
