### ISSUE TITLE
Mock static method in java.* packages not effected using powermock-api-easymock

### ISSUE THREAD

**Issue by sean-chiang** [jayway/powermock#585]
My project use **powermock-module-junit4** and **powermock-api-easymock**.

    <dependency>
    	<groupId>org.powermock</groupId>
    	<artifactId>powermock-api-easymock</artifactId>
    	<version>${powermock.version}</version>
    	<scope>test</scope>
    </dependency>
    <dependency>
    	<groupId>org.powermock</groupId>
    	<artifactId>powermock-module-junit4</artifactId>
    	<version>${powermock.version}</version>
    	<scope>test</scope>
    </dependency>
    
In my project there is a function to handle deadlocked thread. It invokes **java.lang.management.ManagementFactory.getThreadMXBean()** to get a ThreadMXBean instance and then invokes **ThreadMXBean.findDeadlockedThreads()** to find deadlocked threads. 

	long[] tids = ManagementFactory.getThreadMXBean().findDeadlockedThreads();

To do ut, I mock **java.lang.management.ManagementFactory.getThreadMXBean()** to create a ThreadMXBean mock instance, and mock **ThreadMXBean.findDeadlockedThreads()** to return an array of thread IDs.

When I ran ut, I found the **java.lang.management.ManagementFactory.getThreadMXBean()** method not mock correctly. It return a real instance of ThreadMXBean but not the mock.

I guess there maybe something wrong during mocking the **java.lang.management.ManagementFactory** class. So I implemented a static method myself and mock it. It can be mock correctly.

Then I did other tests. I mock **Math.abs()**, failed. I mock **File.listRoots()**, failed again. So I think mockStatic() not work with java.* packages.

Can you please solve this problem? Or give another way to mock java.* packages? Thanks a lot.

If you need, I can commit my test code in comments.

**Comment by sean-chiang** [comment]
sorry, forgot to mention, use powermock 1.6.3

**Comment by johanhaleby** [comment]
Since the classes you're referring to are system classes PowerMock is not able to byte-code manipulate them. You need to use [this](https://github.com/jayway/powermock/wiki/MockSystem) approach instead.

**Comment by sean-chiang** [comment]
Resolved. Thanks very much :)
