### ISSUE TITLE
Is it possible to make Mockito work out of JUnit/Testing environment? 

### ISSUE THREAD

**Issue by seaguest** [jayway/powermock#595]
I am writing a tool (**not for Testing purpose**) based on some existing code (class A, module B here) which I can't touch, I want to mock their behaviours.

I am trying to find something like Mockito for my java application but not under JUnit/Testing environment, or a solution which can make Mockito work out of JUnit/Testing environment.

Here is class A:

    public final class A{  // I can't touch this class, and I can't touch module B where A is called
    	public static String getType(String name){
    		... // DataBase access
    	}
    }

Here is my application:

    public class myApp{
    	public Object compute(String name){
    		// execute module B's code, where A is widely called
    		return computedObject;
    	}
    }

I don't want to access database ihn my aplication, I just want to mock A's method in my java application like Mockito does in JUnit, but I am not able to make it work out of JUnit or find similar framework for java application.

If I use Mockito, then I will have 

    @RunWith(PowerMockRunner.class)
    @PrepareForTest(A.class)  // does this mean Mockito only works under Testing environment?
    public class myApp{	
    	@Test
    	public Object compute(String name){
    		// mock A    		
            // call code in module B
    		return computedObject;
    	}
    }

but I can not call a test method and get its return value from my java application which is not JUnit, JUnitCore can only execute all tests and can't return the value of some Test method.

Could anyone confirm if PowerMockito can work out of Testing environment?

Thanks in advance!

**Comment by witokondoria** [comment]
You could use a tool like AspectJ (https://eclipse.org/aspectj/) to modify those existing functionalities

**Comment by johanhaleby** [comment]
I agree, Aspectj is much better suited for this.
