### ISSUE TITLE
Maybe the Mockito(Legacy) in wiki content table should be adjusted

### ISSUE THREAD

**Issue by madcocomo** [jayway/powermock#607]
At home page of wiki I saw "Mockito (legacy)". It is actually 2 different links to modern usage and legacy usage.
For me it looks like that the usage with Mockito is legacy, and it is not suggested now.  Especially considering that there are 7 items for EasyMock and only 1 for Mockito with a "legacy".
It would be better if we separate it into 2 items, Like:
* Mockito
  * Legacy usage

**Comment by 51systems** [comment]
+1

**Comment by thekingnothing** [comment]
I've updated the wiki home page, so I think it clearer now.
