### ISSUE TITLE
PowerMock.verifyStatic behavior should be better documented

### ISSUE THREAD

**Issue by stantonk** [jayway/powermock#611]
It was not *at all* clear that you have to call the static method you wish to verifyStatic *after* the call to verifyStatic in the docs here:

https://github.com/jayway/powermock/wiki/MockitoUsage#a-full-example-for-mocking-stubbing--verifying-static-method

See this stackoverflow post: http://stackoverflow.com/questions/32976855/powermockito-verifystatic-problems

Not everyone may be familiar with EasyMock as well as Mockito.

**Comment by johanhaleby** [comment]
Please help out and improve the docs. Clone the repo: `git@github.com:jayway/powermock.wiki.git` If that doesn't work (I'm not sure if you can do pull requests on wikis) then perhaps you can write something here and I'll update the docs.

**Comment by thekingnothing** [comment]
I've updated the wiki home page, so I think it clearer now.
