### ISSUE TITLE
Powermock & Mockito 2 

### ISSUE THREAD

**Issue by thekingnothing** [jayway/powermock#613]
As it was discussed in ML Mockito has been moved from Cglib to ByteBuddy. More important that since release 2.0.32-beta cglib classes have been moved out into  separated jar [Mockito#248](https://github.com/mockito/mockito/issues/248).

But PowerMock still depends on classes which have been moved, so users of Powermock get java.lang.NoClassDefFoundError. 

In release 1.6.2 Mockito classes was copied into PowerMock, but not all. To continue support newer version of Mockito: 

- Repack [mockito-cglib](https://github.com/mockito/mockito-cglib) into Powermock mockito-api. I think new module should be created, like mockito2-api
- Next step migrate mockito2-api to ByteBuddy. 

I'm going to create a pull request with repacked mockito-cglib soon.

**Comment by johanhaleby** [comment]
Really cool!! Thanks for your work. I just wonder if it would be possible to somehow extract a "mockito-base" project or similar which is used by both mockito (1) and mockito2? Or is that perhaps a bad idea if they evolve separately?

**Comment by thekingnothing** [comment]
Thanks, but it's not so great job as that is waiting us in future. I mean port Powemock to Bytebuddy. 

I was thinking about extra some common part, but what force me not to do it, that I'm going to change mockito-api and hard to predict what will be changed and what not. 

So, I think better try to extract mockito-base, after mockito2 will be ported to bytebuddy.

**Comment by johanhaleby** [comment]
You're probably right!
