### ISSUE TITLE
Wiki : Release Notes changelog link is wrong

### ISSUE THREAD

**Issue by ryan-gustafson** [jayway/powermock#633]
The changelog link on this wiki page incorrectly points to the Rest Assured changelog.
https://github.com/jayway/powermock/wiki/ReleaseNotes

It should probably point here instead:
https://github.com/jayway/powermock/blob/master/changelog.txt

**Comment by johanhaleby** [comment]
I've fixed it now (but it was pointing to the rest-assured project as far as I could tell). Thanks for pointing out.
