### ISSUE TITLE
Document Maven/Gradle dependencies

### ISSUE THREAD

**Issue by toadzky** [jayway/powermock#664]
It's 2016, why does you documentation have people downloading a zip file with dependencies? You have the modules in Maven, but they are completely scattered through multiple packages with different naming schemes. You should document how to setup different configurations using dependency management.

**Comment by thekingnothing** [comment]
Maven setup is documented for different configuration: EasyMock/Mockito and jUnit/TestNG
https://github.com/jayway/powermock/wiki/GettingStarted#maven-setup

You're welcome to improve PowerMock documentation and add examples for Gradle.
