### ISSUE TITLE
MockingFrameworkReporterFactoryImpl is missing from distributions

### ISSUE THREAD

**Issue by barisdemiroz** [jayway/powermock#667]
I have downloaded PowerMock + mockito archives with dependencies included.

I have written a simple test with annotations `@RunWith(PowerMockRunner.class)` and
`@PrepareForTest(SomeClass.class)`. When I run JUnit I get the following error:

    Extension API internal error: org.powermock.api.extension.reporter.MockingFrameworkReporterFactoryImpl could not be located in classpath.
I looked at the source code and I looked at the jar files, I can't see the mentioned implementation class anywhere. I believe they are missing from the archive files.

I have tried this with both Mockito 1 and 2.

**Comment by thekingnothing** [comment]
Full PowerMock jar doesn't contain the one new module. If you use Maven, you may easy fix the issue by adding: 
```        
    <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-api-mockito-common</artifactId>
            <version>1.6.5</version>
        </dependency>
```

If you need, download jar, you may download it [here](http://central.maven.org/maven2/org/powermock/powermock-api-mockito-common/1.6.5/powermock-api-mockito-common-1.6.5.jar)

Thank you for creating issue. We'll repack release.
