### ISSUE TITLE
powermock whether to support annotation?

### ISSUE THREAD

**Issue by m5jun** [jayway/powermock#683]
annoation can bring many benefits，why powermock don't support annotation?

**Comment by thekingnothing** [comment]
Hmm, could explain your thoughts? Which annotation you want? Do you want mock annotation?

**Comment by thekingnothing** [comment]
Not response for a long time, so close the issue

**Comment by m5jun** [comment]
using Mockito is very convenient, like this:

   `public class DemoTest  {

    @InjectMocks
    private DemoService sut;

    @Mock
    private DependencyObject1 object1;

    @Mock
    private DependencyObject2 object2;

    @Test
    public void testDemo() throws Exception {
        sut.demo();
    }
}
`
