### ISSUE TITLE
PowerMockito not compatible Mockito2 since their v2.0.55-beta release

### ISSUE THREAD

**Issue by mlaffargue** [jayway/powermock#706]
**What steps will reproduce the problem?**

```
@PrepareForTest(ClassWithStaticMethod.class)
public class Test{
    @BeforeClass
    public static void beforeClass() throws Exception {
        PowerMockito.spy(ClassWithStaticMethod.class);
    }
```

**What is the expected output?**
No error

**What do you see instead?**

> java.lang.NoSuchMethodError: org.mockito.internal.handler.MockHandlerFactory.create(Lorg/mockito/mock/MockCreationSettings;)Lorg/mockito/internal/InternalMockHandler;
>   at org.powermock.api.mockito.internal.mockcreation.MockCreator.createMethodInvocationControl(MockCreator.java:121)

**What version of the product are you using?**
JUnit 4.11
Mockito 2.2.8
PowerMockito 1.6.5

**On what operating system?** Windows

**Please provide any additional information below.** 
Since this [modification ](https://github.com/mockito/mockito/commit/019c37c27ed36d2c56c654d6f91e47def217a68e#diff-f75b448bc720abb925b09fc593cb5f9a) which has been tagged on Mockito release [2.0.55-beta](https://github.com/mockito/mockito/blob/v2.0.55-beta/src/main/java/org/mockito/internal/handler/MockHandlerFactory.java) :

`MockHandlerFactory` has been modified from:
`public InternalMockHandler create(MockCreationSettings settings) {`
to:
`public static InternalMockHandler createMockHandler(MockCreationSettings settings) {`

[DefaultMockCreator](https://github.com/jayway/powermock/blob/master/api/mockito2/src/main/java/org/powermock/api/mockito/internal/mockcreation/DefaultMockCreator.java) class still rely on the old version

**Comment by TWiStErRob** [comment]
Similar to #686, would really want to see an upgrade to the final release of Mockito2.

**Comment by thekingnothing** [comment]
Unfortunately, there are so many changes in mockito 2, that PowerMock-Mockito have to be completed overwritten. For me, as one contributor it could take up to 3-4 months.

**Comment by TWiStErRob** [comment]
@szczepiq @TimvdLippe @bric3 @mockito would you be able to help out here so we can use the latest and greatest together?

**Comment by mlaffargue** [comment]
Didn't think it was that far from being compatible. I took Mockito 2.0.42-beta as stated  in the  compatibility section.  Think I should go with Mockito 1 for the moment,  to be able to  enjoy Powermock ?

**Comment by TimvdLippe** [comment]
We did not make that much changes in our public API, I would therefore
expect it to not be such a hassle. However, if Powermock was heavily
relying on the internal workings of Mockito, it is a bit more of a problem.

One of the goals of Mockito 2 (and beyond) is to allow framework/library
authors to hook into Mockito with listeners and such. We are of course very
interested in your usecases and how we can supply a public API for it.

**Comment by TimvdLippe** [comment]
A new feature we have in Mockito 2 is mocking of final methods, so maybe Mockito it sufficient for your usecases. If it is not, we can always take a look to possibly integrate it into Mockito itself and relieve the pressure of the maintainers of PowerMock. Do mind that several testing patterns we will not support, such as constructor mocking and static methods. For these we are convinced there is a different solution that can take use of Mockito features.

So please let us know what features are missing and we can revise whether we want to support it. Some of them wont, maybe we are missing other valid usecases.

**Comment by szczepiq** [comment]
Absolutely we can help. Power mock needs to describe the APIs it needs from Mockito and we will work on exposing them cleanly!

**Comment by szczepiq** [comment]
Also +1 to @TimvdLippe

**Comment by thekingnothing** [comment]
@TimvdLippe @szczepiq  thanks!  

I discussed with @johanhaleby current situation and your suggestion (If you remember I asked you in mail-list). It'll be nice if PowerMock depends only on public, not internal API, but we still have to support Mockito 1and EasyMock.
In the end, we came to thought, that maybe it could be better to remove supporting 3rd part libraries API (classes like `PowerMockito` which enrich `Mockito` class by adding `mockStatic` and so on) with our custom API. 
PowerMock could use `Mockito` under the hood for argument matching (instead Hamcrest matchers), invocation handling and so on.

**Comment by Jacksgong** [comment]
Hi, @thekingnothing thanks for your all guys nice job, But I see the Mockito the latest release version is [2.2.26](https://github.com/mockito/mockito/releases/tag/v2.2.26), what means the **2.0.55-beta version has already been released**.

Although the Mockito 2.x add the new feature to support mock `final` class or `final` method, but it can't handle the case of `static` or others modifiers which PowerMock still be needed to powered.

---

I use the following dependencies:

```
testCompile "org.mockito:mockito-core:2.1.0"
testCompile 'org.powermock:powermock-api-mockito2:1.6.6'
```

But there is a problem still exist #720 , may I know what's your plan to compatible Mockito 2.x?

**Comment by thekingnothing** [comment]
I created roadmap for supporting Mockito 2 and collect all issues in it. So, I'm closing all other issue to have only one place to track Mockito 2 changes.
