### ISSUE TITLE
createPartialMock should support mocking overridden methods in super classes

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#71]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 29, 2008 12:45:40_

If A extends B and both have a method called "mockMe" (A overrides B's
mockMe method) you should be able to specify where in the class hierarchy
the method should be mocked.

_Original issue: http://code.google.com/p/powermock/issues/detail?id=51_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 29, 2008 04:45:48_

**Labels:** -Type-Defect Type-Enhancement

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 31, 2008 01:02:49_

**Status:** Started

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 17, 2008 04:30:33_

Moved to future release

**Labels:** -Milestone-Release1.0 Milestone-Future

**Comment by johanhaleby** [comment]
_From [magnus.p...@gmail.com](https://code.google.com/u/112950871227214842737/) on May 08, 2009 00:57:49_

Do you know in which future release?

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 08, 2009 03:49:20_

Unfortunately not. I've tried to solve this before but I was unable to do so. But now
since it's a requested feature maybe we'll prioritize it a bit more.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 10, 2009 23:23:58_

suppressMethod should also support this

**Labels:** -Milestone-Future Milestone-Release1.3

**Comment by johanhaleby** [comment]
_From [rani....@gmail.com](https://code.google.com/u/113854133344621030890/) on June 11, 2009 03:35:09_

supress method doesnt support this in case the the superclass method is called within
the subclass method that is overiding it. for instance super.xxx()

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on June 11, 2009 03:39:34_

Yes we're aware of this as well

**Comment by johanhaleby** [comment]
_From [rani....@gmail.com](https://code.google.com/u/113854133344621030890/) on June 11, 2009 23:09:16_

So is there any way i can run the test case for a method that overides and calls the
super class method in it?Is there anyway to get rid of the error when the
line..super.xxx() gets called within the method that is tested?

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on June 11, 2009 23:47:56_

You can most definitively test a method that calls super, but unfortunately you
cannot mock/suppress/stub the call to super right now. What you can do however is of
course to mock/stub everything in the super method. If you like the behavior to be
reused you can implement it using a mock policy. I've made an example of this, the
test is here: https://code.google.com/p/powermock/source/browse/trunk/modules/module-test/powermock/junit4-test/src/test/java/samples/junit4/mockpolicy/MockPolicyUsageExampleTest.java which tests: https://code.google.com/p/powermock/source/browse/trunk/tests/utils/src/main/java/samples/mockpolicy/SomeClassWithAMethod.java In the future please use our mailing-list for these kinds of questions (join our
google group and then send an e-mail to powermock@googlegroups.com).

Good luck.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 02, 2009 09:55:31_

Perhaps we could make use of invokeSuper in MethodProxy in CgLib

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 11, 2009 11:24:48_

Will be moved to a future relase

**Labels:** -Milestone-Release1.3 Milestone-Release2.0

**Comment by johanhaleby** [comment]
_From [Mark.FDM...@gmail.com](https://code.google.com/u/111599270328584812591/) on January 16, 2012 11:08:22_

Has this issue been addressed? 

I am having a issue related to this where I am trying to mock a method call to a parent class. Any information would be appreciated. http://stackoverflow.com/questions/8882806/powermokito-issue-with-extended-methods

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 16, 2012 11:37:51_

I don't think it's possible to do this in Java because of the way polymorphism works.

**Comment by johanhaleby** [comment]
_From [Mark.FDM...@gmail.com](https://code.google.com/u/111599270328584812591/) on January 16, 2012 11:41:20_

Thanks for your response Johan. Sort of puts me in a tight spot in the situation I am in. SuppressAll doesn't work, would using a replace with invocation work?

**Comment by johanhaleby** [comment]
_From [hpb...@gmail.com](https://code.google.com/u/103254250676298271970/) on July 25, 2012 02:37:55_

I've made a fix for this issue regarding the suppressing of the super call of the overridden method.

**Attachment:** [powermock-51.patch](http://code.google.com/p/powermock/issues/detail?id=51#hc18)

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 25, 2012 04:23:44_

Issue 364 has been merged into this issue.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 25, 2012 04:25:42_

I've applied the patch to trunk. Please verify!

**Status:** Fixed

**Comment by johanhaleby** [comment]
_From [hpb...@gmail.com](https://code.google.com/u/103254250676298271970/) on July 25, 2012 05:53:05_

The patch also introduces a new class: ClassLocator
Please add this class too (maybe change the package location).

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 25, 2012 06:13:21_

Sorry I forgot it. I've added it now.

**Comment by johanhaleby** [comment]
_From [hpb...@gmail.com](https://code.google.com/u/103254250676298271970/) on July 25, 2012 06:32:56_

I've verified it. Thanks for integrating the patch.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 25, 2012 06:41:37_

Thanks for your help! Would be good if someone else could verify it as well.

**Comment by johanhaleby** [comment]
_From [kkuh...@gmail.com](https://code.google.com/u/100172621127332912380/) on August 02, 2012 12:18:50_

Hi all - Trying to verify this as well. Has this been pushed to public maven repos just yet btw?

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on August 02, 2012 12:31:54_

No it's only available in the trunk. You have to build powermock from the sources. Just do mvn clean install -Dmaven.javadoc.skip=true and you should be fine.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on August 04, 2012 10:53:40_

Issue 399 has been merged into this issue.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on August 04, 2012 10:53:50_

Issue 400 has been merged into this issue.

**Comment by johanhaleby** [comment]
_From [corykend...@gmail.com](https://code.google.com/u/117496643958029087120/) on November 14, 2012 20:03:22_

Is this patch available yet?

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 15, 2012 00:16:09_

No it's only available in the trunk. You have to build powermock from the sources. Just do mvn clean install -Dmaven.javadoc.skip=true and you should be fine.

**Comment by andriydm** [comment]
Is this feature included in latest release?

**Comment by thekingnothing** [comment]
@andriydm, 

As you may see the issue was imported from Google Code and it's hard to understand if it really was include in one of previous release or not. I'll check and let you know.
